### ISSUE TITLE
Weirdness in reading docker-compose.yml

### ISSUE THREAD

**Issue by doanac** [foundriesio/aktualizr-lite#61]
As per:
  https://github.com/foundriesio/aktualizr-lite/blob/a69ec9f7798bb85d500bbab6428cd4fd91ec80ce/src/composeapp.cc#L48-L62

It seems odd we are fork/exec `cat` to read the content of a file. 

Additionally, I've been playing some recently with [yaml-cpp](https://github.com/jbeder/yaml-cpp). Its actually pretty easy to integrate as submodule and hook up with CMake. I think this is probably worth the effort so that we can be more precise.

**Comment by doanac** [comment]
@mike-sul - any thoughts on this?

**Comment by mike-sul** [comment]
> @mike-sul - any thoughts on this?

Absolutely agree that it should be replaced with something that actually parses the docker compose yaml file. I am just hesitant to make any functional changes to aklite further until the simplification&cleaning effort is done and merged to master.
Also, it makes sense to talk to dockerd daemon directly in order to get apps/containers status and eliminate calling docker binary as you suggested, again after the simplifcation effort.

**Comment by doanac** [comment]
This is being address in PR #74
